resources:
  pipelines:
  - pipeline: summarization-app-CI-resource # Name of the pipeline resource.
    source: summarization-app-CI # The name of the pipeline referenced by this pipeline resource.
  - pipeline: summarization-app-infrastructure-resource # Name of the pipeline resource.
    source: summarization-app-infrastructure # The name of the pipeline referenced by this pipeline resource.

variables:
  serviceConnectionName:
  webAppName:

stages:
- stage: Deploy_DEV
  displayName: Deploy Application to Development
  jobs:
  - deployment: DeployAppService
    displayName: 'Deploy to Azure App Service'
    environment: Development
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'specific'
              project: Demo-Project-24-07
              pipelineId: '10'
              buildVersionToDownload: 'latestFromBranch'
              branchName: 'refs/heads/main'
              artifactName: 'SummarizationAPI'
              targetPath: '$(Pipeline.Workspace)/SummarizationAPI'
          - script: echo '$(webAppServiceName)'
          - task: AzureWebApp@1
            displayName: 'Deploy to Azure Web App'
            inputs:
              azureSubscription: $(serviceConnectionName)
              appType: 'webApp'
              appName: '$(webAppServiceName)'
              package: '$(Pipeline.Workspace)/SummarizationAPI/*.zip'
              deploymentMethod: 'auto'
- stage: DeployProd
  displayName: Deploy Application to Production
  jobs:
  - deployment: DeployAppService
    displayName: 'Deploy to Azure App Service'
    environment: 'Production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'specific'
              project: Demo-Project-24-07
              definition: '10'
              buildVersionToDownload: 'latestFromBranch'
              branchName: 'refs/heads/main'
              artifactName: 'SummarizationAPI'
              targetPath: '$(Pipeline.Workspace)/SummarizationAPI'
          - script: echo '$(webAppServiceName)'
          - task: AzureWebApp@1
            displayName: 'Deploy to Azure Web App'
            inputs:
              azureSubscription: $(serviceConnectionName)
              appType: 'webApp'
              appName: '$(webAppServiceName)'
              package: '$(Pipeline.Workspace)/SummarizationAPI/*.zip'
              deploymentMethod: 'auto'