resources:
  pipelines:
  - pipeline: summarization-app-CI # Name of the pipeline resource.
    source: summarization-app-CI # The name of the pipeline referenced by this pipeline resource.
    trigger: true
  - pipeline: summarization-app-infrastructure # Name of the pipeline resource.
    source: summarization-app-infrastructure # The name of the pipeline referenced by this pipeline resource.
    trigger: true

trigger: none

pr: none

pool:
  vmImage: 'windows-latest'

variables:
  serviceConnectionNameProd: azure-stijn-prod-connection
  serviceConnectionNameDev: azure-stijn-dev-connection
  webAppNameProd: u2u-summarization-api-webapp-Production
  webAppNameDev: u2u-summarization-api-webapp-Development

stages:
- stage: Deploy_DEV
  displayName: Deploy Application to Development
  jobs:
  - deployment: DeployAppServiceDev
    displayName: 'Deploy to Azure App Service'
    environment: Development
    strategy:
      runOnce:
        deploy:
          steps:
          - download: summarization-app-CI
            artifact: SummarizationAPI
            patterns: '**'
            displayName: 'Download Pipeline Artifact'
          - task: AzureWebApp@1
            displayName: 'Deploy to Azure Web App'
            inputs:
              azureSubscription: $(serviceConnectionNameDev)
              appType: 'webApp'
              appName: '$(webAppNameDev)'
              package: '$(Pipeline.Workspace)/summarization-app-CI/SummarizationAPI/*.zip'
              deploymentMethod: 'auto'
- stage: DeployProd
  displayName: Deploy Application to Production
  jobs:
  - deployment: DeployAppServiceProd
    displayName: 'Deploy to Azure App Service'
    environment: 'Production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'specific'
              project: Demo-Project-24-07
              definition: '10'
              buildVersionToDownload: 'latestFromBranch'
              branchName: 'refs/heads/main'
              artifactName: 'SummarizationAPI'
              targetPath: '$(Pipeline.Workspace)/SummarizationAPI'
          - script: echo '$(webAppServiceName)'
          - task: AzureWebApp@1
            displayName: 'Deploy to Azure Web App'
            inputs:
              azureSubscription: $(serviceConnectionNameProd)
              appType: 'webApp'
              appName: '$(webAppNameProd)'
              package: '$(Pipeline.Workspace)/summarization-app-CI/SummarizationAPI/*.zip'
              deploymentMethod: 'auto'